server:
  port: 8888
spring:
  application:
    name: grocery-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Anandkrish4204/config-server-repo
          clone-on-start: true
